nelmio_cors:
    defaults:
        allow_credentials: true
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET']
        allow_headers: ['Content-Type', 'Authorization', 'Access-Control-Allow-Origin', 'origin']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/': ~

