nelmio_cors:
    defaults:
        allow_credentials: true
        origin_regex: true
        allow_origin: ['^http://localhost:[0-9]+', '^http://niobey.com/']
        allow_methods: ['GET']
        allow_headers: ['X-Custom-Auth']
        max_age: 3600
    paths:
        '^/api/': ~

